# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/miguel/desktop/ect/4_ano/2_semestre/cr/pratica/xoto8/streampopcount/streampopcount.tmp/streamcopipcore_v1_0_project/StreamCopIPCore_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/miguel/desktop/ect/4_ano/2_semestre/cr/pratica/xoto8/streampopcount/streampopcount.tmp/streamcopipcore_v1_0_project/StreamCopIPCore_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
set_property ip_repo_paths c:/Users/Miguel/Desktop/ECT/4_Ano/2_Semestre/CR/Pratica/xoto8/ip_repo/StreamCopIPCore_1.0 [current_project]
set_property ip_output_repo c:/users/miguel/desktop/ect/4_ano/2_semestre/cr/pratica/xoto8/streampopcount/streampopcount.tmp/streamcopipcore_v1_0_project/StreamCopIPCore_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  c:/Users/Miguel/Desktop/ECT/4_Ano/2_Semestre/CR/Pratica/xoto8/ip_repo/StreamCopIPCore_1.0/hdl/StreamCopIPCore_v1_0_M00_AXIS.vhd
  c:/Users/Miguel/Desktop/ECT/4_Ano/2_Semestre/CR/Pratica/xoto8/ip_repo/StreamCopIPCore_1.0/hdl/StreamCopIPCore_v1_0_S00_AXIS.vhd
  c:/Users/Miguel/Desktop/ECT/4_Ano/2_Semestre/CR/Pratica/xoto8/ip_repo/StreamCopIPCore_1.0/hdl/StreamCopIPCore_v1_0.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top StreamCopIPCore_v1_0 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef StreamCopIPCore_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file StreamCopIPCore_v1_0_utilization_synth.rpt -pb StreamCopIPCore_v1_0_utilization_synth.pb"
